// تنفيذ — التعبئة في اعتماد | Etimad field metadata
// Hand-trimmed from docs/product/etimad-fill-contract.json (meta-repo).
// key = the Etimad DOM `name` attribute. control ∈
//   text | number | textarea | select | multiselect | radio | checkbox | date | data
// "data" = read-only/derived on Etimad's side — the fill engine skips it.
// "date" = text input paired with a "ميلادي" toggle checkbox named cb_<key>;
//          the payload may carry a companion hint key "<key>__calendar"
//          with the value "هجري" or "ميلادي".
// Fields repeated across wizard steps keep the step where they are editable.

"use strict";

const ETIMAD_FIELD_META = {
  // ── الخطوة ١: المعلومات الأساسية (basic) ─────────────────────────────
  TenderTypeId: { control: "select", step: "basic" },
  ReasonForLimitedTenderTypeId: { control: "select", step: "basic" },
  ReasonForPurchaseTenderTypeId: { control: "select", step: "basic" },
  EstimatedValueassignedUserId: { control: "select", step: "basic" },
  TenderName: { control: "text", step: "basic" },
  ReferenceNumber: { control: "data", step: "basic" },
  TenderNumber: { control: "text", step: "basic" },
  ConditionsBookletPrice: { control: "number", step: "basic" },
  TenderTypeOtherSelectionReason: { control: "text", step: "basic" },
  TechnicalOrganizationId: { control: "select", step: "basic" },
  OffersOpeningCommitteeId: { control: "select", step: "basic" },
  OffersCheckingCommitteeId: { control: "select", step: "basic" },
  OffersOpenCheckingCommitteeId: { control: "select", step: "basic" },
  VROCommitteeId: { control: "select", step: "basic" },
  IsExcluedFromUnifiedPurchase: { control: "radio", step: "basic" },
  IsUnitApprovedExcludedRequest: { control: "radio", step: "basic" },
  IsLinkedToAnnouncement: { control: "checkbox", step: "basic" },
  PreAnnouncementId: { control: "select", step: "basic" },
  AnnouncementTemplateId: { control: "select", step: "basic" },
  QualificationType: { control: "radio", step: "basic" },
  HasQualification: { control: "checkbox", step: "basic" },
  HasInternalPreQualification: { control: "radio", step: "basic" },
  PreQualificationId: { control: "select", step: "basic" },
  ExternalPreQualificationReference: { control: "text", step: "basic" },
  OfferPresentationWayId: { control: "radio", step: "basic" },
  InvitationTypeId: { control: "radio", step: "basic" },
  SupplierNeedSample: { control: "radio", step: "basic" },
  SamplesDeliveryAddress: { control: "text", step: "basic" },
  AgreementTypeId: { control: "radio", step: "basic" },
  AgreementDays: { control: "number", step: "basic" },
  AgreementMonthes: { control: "number", step: "basic" },
  AgreementYears: { control: "number", step: "basic" },
  TenderAgreementAgencyIDs: { control: "multiselect", step: "basic" },
  NumberOfWinners: { control: "number", step: "basic" },
  BonusValue: { control: "number", step: "basic" },
  Purpose: { control: "textarea", step: "basic" },
  EstimatedValue: { control: "number", step: "basic" },
  EstimationRequestDuration: { control: "number", step: "basic" },
  EstimatedValueRange: { control: "text", step: "basic" },
  IsLowBudgetDirectPurchase: { control: "radio", step: "basic" },
  DirectPurchaseCommitteeId: { control: "select", step: "basic" },
  DirectPurchaseCommitteeMemberId: { control: "select", step: "basic" },
  IsProjectInsurance: { control: "radio", step: "basic" },
  EstimatedIncome: { control: "number", step: "basic" },
  GovDirectFinancialCosts: { control: "number", step: "basic" },
  AgencyBudgetProjectNumber: { control: "data", step: "basic" },

  // ── الخطوة ٢: مجال التصنيف وموقع التنفيذ (classification) ───────────
  InsideKSA: { control: "radio", step: "classification" },
  TenderAreaIDs: { control: "multiselect", step: "classification" },
  TenderCityIDs: { control: "multiselect", step: "classification" },
  TenderCountriesIDs: { control: "multiselect", step: "classification" },
  NeedFinalGuarantee: { control: "radio", step: "classification" },
  FinalGuaranteePercentage: { control: "number", step: "classification" },
  AwardingStoppingPeriod: { control: "number", step: "classification" },
  NeedInitialGuarantee: { control: "radio", step: "classification" },
  InitialGuaranteePercentage: { control: "number", step: "classification" },
  InitialGuaranteeAddress: { control: "text", step: "classification" },
  GuaranteeApprovalReferenceId: { control: "text", step: "classification" },
  Details: { control: "textarea", step: "classification" },
  TenderConstructionWorkIDs: { control: "multiselect", step: "classification" },
  TenderMentainanceRunnigWorkIDs: { control: "multiselect", step: "classification" },
  TenderActivitieIDs: { control: "multiselect", step: "classification" },
  IsTawreed: { control: "checkbox", step: "classification" },
  TemplateYears: { control: "select", step: "classification" },
  ActivityDescription: { control: "textarea", step: "classification" },

  // ── الخطوة ٣: العناوين والمواعيد (datesAddresses) ────────────────────
  OffersOpeningAddressId: { control: "select", step: "datesAddresses" },
  OffersOpeningAddress: { control: "text", step: "datesAddresses" },
  BuildingName: { control: "text", step: "datesAddresses" },
  FloarNumber: { control: "text", step: "datesAddresses" },
  DepartmentName: { control: "text", step: "datesAddresses" },
  DeliveryDate: { control: "date", step: "datesAddresses" },
  DeliveryTime: { control: "text", step: "datesAddresses" },
  IsSampleAddresSameOffersAddress: { control: "checkbox", step: "datesAddresses" },
  OfferDeliveryAddress: { control: "text", step: "datesAddresses" },
  OfferBuildingName: { control: "text", step: "datesAddresses" },
  OfferFloarNumber: { control: "text", step: "datesAddresses" },
  OfferDepartmentName: { control: "text", step: "datesAddresses" },
  OffersDeliveryDate: { control: "date", step: "datesAddresses" },
  OffersDeliveryTime: { control: "text", step: "datesAddresses" },
  NumberOfDaysForReceivingInquiries: { control: "number", step: "datesAddresses" },
  NumberOfDaysForOfferPresentation: { control: "number", step: "datesAddresses" },
  AwardingExpectedDate: { control: "date", step: "datesAddresses" },
  StartingBusinessOrServicesDate: { control: "date", step: "datesAddresses" },
  ContractDurationType: { control: "select", step: "datesAddresses" },
  contractDuration: { control: "number", step: "datesAddresses" },

  // ── الخطوة ٤: تجزئة المنافسة (fragmentation) ─────────────────────────
  groupName: { control: "text", step: "fragmentation" },
  groupDescription: { control: "textarea", step: "fragmentation" },
  IsDivisible: { control: "radio", step: "fragmentation" },
  DivisionReason: { control: "textarea", step: "fragmentation" },
  ClassificationFieldId: { control: "select", step: "fragmentation" },

  // ── الخطوة ٥: مراجعة هيئة كفاءة الإنفاق (spendingEfficiency) ─────────
  SpendingEfficiencyAuthorityApprovalFileNetId: { control: "text", step: "spendingEfficiency" },
  IsIncludeSymmetricItems: { control: "radio", step: "spendingEfficiency" },
  IsUnitApprovedSymmetricItems: { control: "radio", step: "spendingEfficiency" },
  SymmetricItemsUnitApprovalFileNetId: { control: "text", step: "spendingEfficiency" },
  IsIncludeTradeMark: { control: "radio", step: "spendingEfficiency" },
  IsUnitApprovedTradeMark: { control: "radio", step: "spendingEfficiency" },
  TradeMarkUnitApprovalFileNetId: { control: "text", step: "spendingEfficiency" },

  // ── الخطوة ٦: جداول الكميات (quantityTables) ─────────────────────────
  HasAlternativeOffer: { control: "radio", step: "quantityTables" },

  // ── الخطوة ٧: ملفات المنافسة / الكراسة (bookletFiles) ────────────────
  Description: { control: "textarea", step: "bookletFiles" },
  HideCerificatesIDs: { control: "checkbox", step: "bookletFiles" },
  CerificatesIDs: { control: "multiselect", step: "bookletFiles" },
  AgentName: { control: "text", step: "bookletFiles" },
  AgentPhone: { control: "text", step: "bookletFiles" },
  AgentFax: { control: "text", step: "bookletFiles" },
  AgentJob: { control: "text", step: "bookletFiles" },
  AgentEmail: { control: "text", step: "bookletFiles" },
  AgencyDecalration: { control: "text", step: "bookletFiles" },
  LocalContentMechanismIDs: { control: "multiselect", step: "bookletFiles" },
  IsApplyProvisionsMandatoryList: { control: "checkbox", step: "bookletFiles" },
  MinimumBaseline: { control: "text", step: "bookletFiles" },
  MinimumPercentageLocalContentTarget: { control: "text", step: "bookletFiles" },
  StudyMinimumTargetFileNetReferenceId: { control: "text", step: "bookletFiles" },
  LocalContentAgreementFileNetReferenceId: { control: "text", step: "bookletFiles" },
  IsSolidarity: { control: "radio", step: "bookletFiles" },
  RequiresSpecializedTechCapabilities: { control: "radio", step: "bookletFiles" },
  MaxTimeToAnswerQuestions: { control: "number", step: "bookletFiles" },
  AlternativeEmailForCommuncation: { control: "text", step: "bookletFiles" },
  TechnicalOfferDocuments: { control: "data", step: "bookletFiles" },
  FinancialOfferDocuments: { control: "data", step: "bookletFiles" },
  DocumentStyle: { control: "textarea", step: "bookletFiles" },
  AllowancePeriodToAddOffersIfNotAddedBeofre: { control: "text", step: "bookletFiles" },
  OffersEvaluationCriteria: { control: "text", step: "bookletFiles" },
  OffersChecking: { control: "text", step: "bookletFiles" },
  AllowedOfferSiningDays: { control: "text", step: "bookletFiles" },
  WritePrice: { control: "textarea", step: "bookletFiles" },
  PenaltiesText: { control: "textarea", step: "bookletFiles" },
  LateWorkPenaltiesRulesText: { control: "textarea", step: "bookletFiles" },
  PenaltiesOfLateValue: { control: "text", step: "bookletFiles" },
  technicalPassingMechanismWay: { control: "radio", step: "bookletFiles" },
  // `isLevelTwo` ليس بيانات — هو مبدّل وضع في نموذج إضافة المعيار
  // (ثانٍ/ثالث)، يقوده etimad-criteria.js أثناء الإضافة. إدراجه كحقل قابل
  // للتعبئة يجعل المحرك المسطّح يزاحم المُضيف على نفس الزر.
  //
  // كذلك حقول معايير التقييم الرقمية (txtTechnicalPassingRate،
  // technicalEvaluationWeight، financialEvaluationWeight) لها id بلا name،
  // وحقول الوزن النهائي معرّفاتها مُولَّدة — كلها في etimad-criteria.js.
  ProjectsScope: { control: "textarea", step: "bookletFiles" },
  WorksProgram: { control: "textarea", step: "bookletFiles" },
  WorkLocationDetails: { control: "textarea", step: "bookletFiles" },
  ServicesAndWorkImplementationsMethod: { control: "textarea", step: "bookletFiles" },
  YearsNumberOfProfessionalExperienceForSaudis: { control: "number", step: "bookletFiles" },
  WorkforceSpecifications: { control: "textarea", step: "bookletFiles" },
  QualitySpecifications: { control: "textarea", step: "bookletFiles" },
  SafetySpecifications: { control: "textarea", step: "bookletFiles" },
  IsIncludeTrainingAndknowledge: { control: "radio", step: "bookletFiles" },
  InsuranceRequirements: { control: "textarea", step: "bookletFiles" },
  SpecialConditions: { control: "textarea", step: "bookletFiles" },
  QualificationCriteriaAttachmentNumber: { control: "number", step: "bookletFiles" },
  Attachments: { control: "textarea", step: "bookletFiles" },
};
