import { Contract } from "./types/contract";

export const dummyContracts: Contract[] = [
    {
        id: "1",
        name: "مشروع صيانة وتطوير شبكات الجامعة",
        contractNumber: "CONT-2026-001",
        serialNumber: "SN-998877",
        contractorName: "مؤسسة الرائد للمقاولات",
        projectOwnerName: "إدارة المرافق",
        responsibleEmployee: "أحمد محمد العلي",
        supervisingDepartment: "قسم الهندسة",
        contractStatus: "نشط",
        year: "2026",
        contractValue: 5000000,
        amendedValue: 5500000,
        bankGuaranteeValue: 250000,
        spentAmount: 1250000,
        completionPercentage: 25,
        spentPercentageFromContract: 22.7,
        signingDate: "2026-01-15",
        startDate: "2026-02-01",
        endDate: "2027-02-01",
        initialDeliveryDate: "2027-01-15",
        finalDeliveryDate: "2027-02-15",
        amendmentOrderDate: "2026-06-01",
        tenderNotificationDate: "2025-11-01",
        tenderDate: "2025-12-01",
        bankGuaranteeEndDate: "2028-02-01",
        contractAmendedDurationEndDate: "2027-03-01",
        awardingCommitteeSignatureDate: "2025-12-15",
        tenderOpeningDate: "2025-12-05",
        amendmentOrdersCount: 1,
        contractDuration: "12 شهر",
        amendedContractDuration: "13 شهر",
        tenderCommitteeNumber: "TC-2025-45",
        purchaseOrderNumber: "PO-8855",
        projectClassification: "إنشاءات",
        tenderType: "عامة",
        competitionReferenceNumber: "COMP-2025-099",
        bankGuaranteeReferenceNumber: "BANK-G-112233",
        projectType: "تشغيل وصيانة",
        sapPurchaseRequestNumber: "SAP-99001122"
    },
    {
        id: "2",
        name: "توريد أجهزة حاسب آلي",
        contractNumber: "CONT-2026-002",
        serialNumber: "SN-112233",
        contractorName: "شركة الحلول الرقمية",
        projectOwnerName: "إدارة تقنية المعلومات",
        responsibleEmployee: "سارة عبد الله",
        supervisingDepartment: "قسم التوريدات",
        contractStatus: "تحت الترسية",
        year: "2026",
        contractValue: 1200000,
        amendedValue: 0,
        bankGuaranteeValue: 60000,
        spentAmount: 0,
        completionPercentage: 0,
        spentPercentageFromContract: 0,
        signingDate: "2026-03-10",
        startDate: "2026-04-01",
        endDate: "2026-10-01",
        initialDeliveryDate: null as unknown as string,
        finalDeliveryDate: null as unknown as string,
        amendmentOrderDate: null as unknown as string,
        tenderNotificationDate: "2026-01-10",
        tenderDate: "2026-02-15",
        bankGuaranteeEndDate: "2027-04-01",
        contractAmendedDurationEndDate: null as unknown as string,
        awardingCommitteeSignatureDate: "2026-02-28",
        tenderOpeningDate: "2026-02-20",
        amendmentOrdersCount: 0,
        contractDuration: "6 أشهر",
        amendedContractDuration: "",
        tenderCommitteeNumber: "TC-2026-12",
        purchaseOrderNumber: "PO-4433",
        projectClassification: "تجهيزات مكتبية",
        tenderType: "محدودة",
        competitionReferenceNumber: "COMP-2026-012",
        bankGuaranteeReferenceNumber: "BANK-G-445566",
        projectType: "توريدات",
        sapPurchaseRequestNumber: "SAP-55667788"
    }
];